name: Build desktop

on:
  push:
    branches:
      - release-desktop

defaults:
  run:
    working-directory: desktop

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: install
        run: |
          cd ..
          rm yarn.lock
          bun link
          bun install
          bun bundle

      - name: build portable
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'win')
        run: |
          bun electron-vite build
        env:
          VITE_BUILD_TARGET: portable
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: zip portable
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          bun electron-builder --publish never
          zip -r dist/linux-unpacked.zip dist/linux-unpacked

      - name: pkg appx on windows
        if: startsWith(matrix.os, 'win')
        run: |
          bun electron-builder --publish never --win appx

      - name: zip portable
        if: startsWith(matrix.os, 'win')
        run: Compress-Archive -Path "dist\win-unpacked\*" -DestinationPath "dist\win-unpacked.zip"
        shell: powershell

      - name: build
        run: bun electron-vite build
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: pkg on mac
        if: startsWith(matrix.os, 'mac')
        run: |
          echo -n "${{ secrets.INSTALLER_CERT }}" | base64 -d > installer.cer
          echo -n "${{ secrets.APPLICATION_CERT }}" | base64 -d > application.cer
          sudo security add-trusted-cert -d -r trustRoot -k ~/Library/Keychains/login.keychain installer.cer
          sudo security add-trusted-cert -d -r trustRoot -k ~/Library/Keychains/login.keychain application.cer
          bun electron-builder --x64 --arm64 --publish never
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Install Snapcraft
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo snap install snapcraft --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: pkg on ubuntu & windows
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'win')
        run: bun electron-builder --publish never

      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}
          path: |
            desktop/dist/latest.yml
            desktop/dist/latest-*.yml
            desktop/dist/*.AppImage
            desktop/dist/*.snap
            desktop/dist/*.appx
            desktop/dist/*.blockmap
            desktop/dist/*.dmg
            desktop/dist/*.exe
            desktop/dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: prepare release note
        run: |
          VER=$(jq -r '.version' package.json)
          sed -i "s/{VER}/$VER/g" changelogs/template.txt
          cat changelogs/template.txt changelogs/v$VER.txt > note.txt
          echo "TAG=v$VER" >> $GITHUB_ENV

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: desktop/note.txt
          files: dist/*
          repository: nonbili/NouTube-Desktop
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          tag_name: ${{ env.TAG }}
